/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DesabonnementRouteImport } from './routes/desabonnement'
import { Route as LivreurRouteImport } from './routes/livreur'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugBorneRouteImport } from './routes/$slug.borne'
import { Route as SlugCgvRouteImport } from './routes/$slug.cgv'
import { Route as SlugCommandeRouteImport } from './routes/$slug.commande'
import { Route as SlugConfidentialiteRouteImport } from './routes/$slug.confidentialite'
import { Route as SlugCookiesRouteImport } from './routes/$slug.cookies'
import { Route as SlugCuisineRouteImport } from './routes/$slug.cuisine'
import { Route as SlugMentionsLegalesRouteImport } from './routes/$slug.mentions-legales'
import { Route as SlugReserverRouteImport } from './routes/$slug.reserver'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiMenuPhotoGenerateRouteImport } from './routes/api/menu-photo-generate'
import { Route as CuisineIndexRouteImport } from './routes/cuisine.index'
import { Route as CuisineSplatRouteImport } from './routes/cuisine.$'
import { Route as SuiviIdRouteImport } from './routes/suivi.$id'
import { Route as SlugSuiviIdRouteImport } from './routes/$slug.suivi.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSlugRouteImport } from './routes/_authenticated/admin.$slug'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminQrcodesRouteImport } from './routes/_authenticated/admin.qrcodes'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedEspaceFacturesRouteImport } from './routes/_authenticated/espace.factures'
import { Route as AuthenticatedEspaceTableauDeBordRouteImport } from './routes/_authenticated/espace.tableau-de-bord'
import { Route as ApiPublicLyraIpnRouteImport } from './routes/api/public/lyra-ipn'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as ApiPublicMollieWebhookRouteImport } from './routes/api/public/mollie-webhook'
import { Route as AuthenticatedEspaceSlugIndexRouteImport } from './routes/_authenticated/espace.$slug.index'
import { Route as AuthenticatedEspaceSlugCarteRouteImport } from './routes/_authenticated/espace.$slug.carte'
import { Route as AuthenticatedEspaceSlugClientsRouteImport } from './routes/_authenticated/espace.$slug.clients'
import { Route as AuthenticatedEspaceSlugEquipeRouteImport } from './routes/_authenticated/espace.$slug.equipe'
import { Route as AuthenticatedEspaceSlugLivraisonRouteImport } from './routes/_authenticated/espace.$slug.livraison'
import { Route as AuthenticatedEspaceSlugQrRouteImport } from './routes/_authenticated/espace.$slug.qr'
import { Route as AuthenticatedEspaceSlugReglagesRouteImport } from './routes/_authenticated/espace.$slug.reglages'
import { Route as AuthenticatedEspaceSlugReservationsRouteImport } from './routes/_authenticated/espace.$slug.reservations'
import { Route as ApiPublicPushMessageRouteImport } from './routes/api/public/push/message'
import { Route as ApiPublicRestaurantBannerIdRouteImport } from './routes/api/public/restaurant-banner/$id'
import { Route as ApiPublicVapiRestaurantIdRouteImport } from './routes/api/public/vapi.$restaurantId'
import { Route as ApiPublicMenuPhotoRestaurantIdFileRouteImport } from './routes/api/public/menu-photo.$restaurantId.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceRoute = AgenceRouteImport.update({
  id: '/agence',
  path: '/agence',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DesabonnementRoute = DesabonnementRouteImport.update({
  id: '/desabonnement',
  path: '/desabonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreurRoute = LivreurRouteImport.update({
  id: '/livreur',
  path: '/livreur',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugBorneRoute = SlugBorneRouteImport.update({
  id: '/borne',
  path: '/borne',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCgvRoute = SlugCgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCommandeRoute = SlugCommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => SlugRoute,
} as any)
const SlugConfidentialiteRoute = SlugConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCookiesRoute = SlugCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCuisineRoute = SlugCuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => SlugRoute,
} as any)
const SlugMentionsLegalesRoute = SlugMentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => SlugRoute,
} as any)
const SlugReserverRoute = SlugReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiMenuPhotoGenerateRoute = ApiMenuPhotoGenerateRouteImport.update({
  id: '/api/menu-photo-generate',
  path: '/api/menu-photo-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineIndexRoute = CuisineIndexRouteImport.update({
  id: '/cuisine/',
  path: '/cuisine/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineSplatRoute = CuisineSplatRouteImport.update({
  id: '/cuisine/$',
  path: '/cuisine/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIdRoute = SuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSuiviIdRoute = SlugSuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => SlugRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSlugRoute = AuthenticatedAdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQrcodesRoute =
  AuthenticatedAdminQrcodesRouteImport.update({
    id: '/qrcodes',
    path: '/qrcodes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/espace/',
    path: '/espace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceFacturesRoute =
  AuthenticatedEspaceFacturesRouteImport.update({
    id: '/espace/factures',
    path: '/espace/factures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceTableauDeBordRoute =
  AuthenticatedEspaceTableauDeBordRouteImport.update({
    id: '/espace/tableau-de-bord',
    path: '/espace/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicLyraIpnRoute = ApiPublicLyraIpnRouteImport.update({
  id: '/api/public/lyra-ipn',
  path: '/api/public/lyra-ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMollieWebhookRoute = ApiPublicMollieWebhookRouteImport.update({
  id: '/api/public/mollie-webhook',
  path: '/api/public/mollie-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceSlugIndexRoute =
  AuthenticatedEspaceSlugIndexRouteImport.update({
    id: '/espace/$slug/',
    path: '/espace/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugCarteRoute =
  AuthenticatedEspaceSlugCarteRouteImport.update({
    id: '/espace/$slug/carte',
    path: '/espace/$slug/carte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugClientsRoute =
  AuthenticatedEspaceSlugClientsRouteImport.update({
    id: '/espace/$slug/clients',
    path: '/espace/$slug/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugEquipeRoute =
  AuthenticatedEspaceSlugEquipeRouteImport.update({
    id: '/espace/$slug/equipe',
    path: '/espace/$slug/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugLivraisonRoute =
  AuthenticatedEspaceSlugLivraisonRouteImport.update({
    id: '/espace/$slug/livraison',
    path: '/espace/$slug/livraison',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugQrRoute =
  AuthenticatedEspaceSlugQrRouteImport.update({
    id: '/espace/$slug/qr',
    path: '/espace/$slug/qr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugReglagesRoute =
  AuthenticatedEspaceSlugReglagesRouteImport.update({
    id: '/espace/$slug/reglages',
    path: '/espace/$slug/reglages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEspaceSlugReservationsRoute =
  AuthenticatedEspaceSlugReservationsRouteImport.update({
    id: '/espace/$slug/reservations',
    path: '/espace/$slug/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPushMessageRoute = ApiPublicPushMessageRouteImport.update({
  id: '/api/public/push/message',
  path: '/api/public/push/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRestaurantBannerIdRoute =
  ApiPublicRestaurantBannerIdRouteImport.update({
    id: '/api/public/restaurant-banner/$id',
    path: '/api/public/restaurant-banner/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVapiRestaurantIdRoute =
  ApiPublicVapiRestaurantIdRouteImport.update({
    id: '/api/public/vapi/$restaurantId',
    path: '/api/public/vapi/$restaurantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMenuPhotoRestaurantIdFileRoute =
  ApiPublicMenuPhotoRestaurantIdFileRouteImport.update({
    id: '/api/public/menu-photo/$restaurantId/$file',
    path: '/api/public/menu-photo/$restaurantId/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/agence': typeof AgenceRoute
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/desabonnement': typeof DesabonnementRoute
  '/livreur': typeof LivreurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/borne': typeof SlugBorneRoute
  '/$slug/cgv': typeof SlugCgvRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/$slug/confidentialite': typeof SlugConfidentialiteRoute
  '/$slug/cookies': typeof SlugCookiesRoute
  '/$slug/cuisine': typeof SlugCuisineRoute
  '/$slug/mentions-legales': typeof SlugMentionsLegalesRoute
  '/$slug/reserver': typeof SlugReserverRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/menu-photo-generate': typeof ApiMenuPhotoGenerateRoute
  '/cuisine/$': typeof CuisineSplatRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
  '/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/espace/tableau-de-bord': typeof AuthenticatedEspaceTableauDeBordRoute
  '/api/public/lyra-ipn': typeof ApiPublicLyraIpnRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mollie-webhook': typeof ApiPublicMollieWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/espace/$slug/carte': typeof AuthenticatedEspaceSlugCarteRoute
  '/espace/$slug/clients': typeof AuthenticatedEspaceSlugClientsRoute
  '/espace/$slug/equipe': typeof AuthenticatedEspaceSlugEquipeRoute
  '/espace/$slug/livraison': typeof AuthenticatedEspaceSlugLivraisonRoute
  '/espace/$slug/qr': typeof AuthenticatedEspaceSlugQrRoute
  '/espace/$slug/reglages': typeof AuthenticatedEspaceSlugReglagesRoute
  '/espace/$slug/reservations': typeof AuthenticatedEspaceSlugReservationsRoute
  '/api/public/push/message': typeof ApiPublicPushMessageRoute
  '/api/public/restaurant-banner/$id': typeof ApiPublicRestaurantBannerIdRoute
  '/api/public/vapi/$restaurantId': typeof ApiPublicVapiRestaurantIdRoute
  '/espace/$slug/': typeof AuthenticatedEspaceSlugIndexRoute
  '/api/public/menu-photo/$restaurantId/$file': typeof ApiPublicMenuPhotoRestaurantIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/desabonnement': typeof DesabonnementRoute
  '/livreur': typeof LivreurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/borne': typeof SlugBorneRoute
  '/$slug/cgv': typeof SlugCgvRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/$slug/confidentialite': typeof SlugConfidentialiteRoute
  '/$slug/cookies': typeof SlugCookiesRoute
  '/$slug/cuisine': typeof SlugCuisineRoute
  '/$slug/mentions-legales': typeof SlugMentionsLegalesRoute
  '/$slug/reserver': typeof SlugReserverRoute
  '/api/menu-photo-generate': typeof ApiMenuPhotoGenerateRoute
  '/cuisine/$': typeof CuisineSplatRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug': typeof SlugIndexRoute
  '/cuisine': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
  '/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/espace/tableau-de-bord': typeof AuthenticatedEspaceTableauDeBordRoute
  '/api/public/lyra-ipn': typeof ApiPublicLyraIpnRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mollie-webhook': typeof ApiPublicMollieWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/espace/$slug/carte': typeof AuthenticatedEspaceSlugCarteRoute
  '/espace/$slug/clients': typeof AuthenticatedEspaceSlugClientsRoute
  '/espace/$slug/equipe': typeof AuthenticatedEspaceSlugEquipeRoute
  '/espace/$slug/livraison': typeof AuthenticatedEspaceSlugLivraisonRoute
  '/espace/$slug/qr': typeof AuthenticatedEspaceSlugQrRoute
  '/espace/$slug/reglages': typeof AuthenticatedEspaceSlugReglagesRoute
  '/espace/$slug/reservations': typeof AuthenticatedEspaceSlugReservationsRoute
  '/api/public/push/message': typeof ApiPublicPushMessageRoute
  '/api/public/restaurant-banner/$id': typeof ApiPublicRestaurantBannerIdRoute
  '/api/public/vapi/$restaurantId': typeof ApiPublicVapiRestaurantIdRoute
  '/espace/$slug': typeof AuthenticatedEspaceSlugIndexRoute
  '/api/public/menu-photo/$restaurantId/$file': typeof ApiPublicMenuPhotoRestaurantIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRouteWithChildren
  '/agence': typeof AgenceRoute
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/desabonnement': typeof DesabonnementRoute
  '/livreur': typeof LivreurRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$slug/borne': typeof SlugBorneRoute
  '/$slug/cgv': typeof SlugCgvRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/$slug/confidentialite': typeof SlugConfidentialiteRoute
  '/$slug/cookies': typeof SlugCookiesRoute
  '/$slug/cuisine': typeof SlugCuisineRoute
  '/$slug/mentions-legales': typeof SlugMentionsLegalesRoute
  '/$slug/reserver': typeof SlugReserverRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/menu-photo-generate': typeof ApiMenuPhotoGenerateRoute
  '/cuisine/$': typeof CuisineSplatRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
  '/_authenticated/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/qrcodes': typeof AuthenticatedAdminQrcodesRoute
  '/_authenticated/espace/factures': typeof AuthenticatedEspaceFacturesRoute
  '/_authenticated/espace/tableau-de-bord': typeof AuthenticatedEspaceTableauDeBordRoute
  '/api/public/lyra-ipn': typeof ApiPublicLyraIpnRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/api/public/mollie-webhook': typeof ApiPublicMollieWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/espace/$slug/carte': typeof AuthenticatedEspaceSlugCarteRoute
  '/_authenticated/espace/$slug/clients': typeof AuthenticatedEspaceSlugClientsRoute
  '/_authenticated/espace/$slug/equipe': typeof AuthenticatedEspaceSlugEquipeRoute
  '/_authenticated/espace/$slug/livraison': typeof AuthenticatedEspaceSlugLivraisonRoute
  '/_authenticated/espace/$slug/qr': typeof AuthenticatedEspaceSlugQrRoute
  '/_authenticated/espace/$slug/reglages': typeof AuthenticatedEspaceSlugReglagesRoute
  '/_authenticated/espace/$slug/reservations': typeof AuthenticatedEspaceSlugReservationsRoute
  '/api/public/push/message': typeof ApiPublicPushMessageRoute
  '/api/public/restaurant-banner/$id': typeof ApiPublicRestaurantBannerIdRoute
  '/api/public/vapi/$restaurantId': typeof ApiPublicVapiRestaurantIdRoute
  '/_authenticated/espace/$slug/': typeof AuthenticatedEspaceSlugIndexRoute
  '/api/public/menu-photo/$restaurantId/$file': typeof ApiPublicMenuPhotoRestaurantIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/agence'
    | '/commande'
    | '/connexion'
    | '/desabonnement'
    | '/livreur'
    | '/reset-password'
    | '/$slug/borne'
    | '/$slug/cgv'
    | '/$slug/commande'
    | '/$slug/confidentialite'
    | '/$slug/cookies'
    | '/$slug/cuisine'
    | '/$slug/mentions-legales'
    | '/$slug/reserver'
    | '/admin'
    | '/api/menu-photo-generate'
    | '/cuisine/$'
    | '/suivi/$id'
    | '/$slug/'
    | '/cuisine/'
    | '/$slug/suivi/$id'
    | '/admin/$slug'
    | '/admin/clients'
    | '/admin/qrcodes'
    | '/espace/factures'
    | '/espace/tableau-de-bord'
    | '/api/public/lyra-ipn'
    | '/api/public/manifest'
    | '/api/public/mollie-webhook'
    | '/admin/'
    | '/espace/'
    | '/espace/$slug/carte'
    | '/espace/$slug/clients'
    | '/espace/$slug/equipe'
    | '/espace/$slug/livraison'
    | '/espace/$slug/qr'
    | '/espace/$slug/reglages'
    | '/espace/$slug/reservations'
    | '/api/public/push/message'
    | '/api/public/restaurant-banner/$id'
    | '/api/public/vapi/$restaurantId'
    | '/espace/$slug/'
    | '/api/public/menu-photo/$restaurantId/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence'
    | '/commande'
    | '/connexion'
    | '/desabonnement'
    | '/livreur'
    | '/reset-password'
    | '/$slug/borne'
    | '/$slug/cgv'
    | '/$slug/commande'
    | '/$slug/confidentialite'
    | '/$slug/cookies'
    | '/$slug/cuisine'
    | '/$slug/mentions-legales'
    | '/$slug/reserver'
    | '/api/menu-photo-generate'
    | '/cuisine/$'
    | '/suivi/$id'
    | '/$slug'
    | '/cuisine'
    | '/$slug/suivi/$id'
    | '/admin/$slug'
    | '/admin/clients'
    | '/admin/qrcodes'
    | '/espace/factures'
    | '/espace/tableau-de-bord'
    | '/api/public/lyra-ipn'
    | '/api/public/manifest'
    | '/api/public/mollie-webhook'
    | '/admin'
    | '/espace'
    | '/espace/$slug/carte'
    | '/espace/$slug/clients'
    | '/espace/$slug/equipe'
    | '/espace/$slug/livraison'
    | '/espace/$slug/qr'
    | '/espace/$slug/reglages'
    | '/espace/$slug/reservations'
    | '/api/public/push/message'
    | '/api/public/restaurant-banner/$id'
    | '/api/public/vapi/$restaurantId'
    | '/espace/$slug'
    | '/api/public/menu-photo/$restaurantId/$file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/agence'
    | '/commande'
    | '/connexion'
    | '/desabonnement'
    | '/livreur'
    | '/reset-password'
    | '/$slug/borne'
    | '/$slug/cgv'
    | '/$slug/commande'
    | '/$slug/confidentialite'
    | '/$slug/cookies'
    | '/$slug/cuisine'
    | '/$slug/mentions-legales'
    | '/$slug/reserver'
    | '/_authenticated/admin'
    | '/api/menu-photo-generate'
    | '/cuisine/$'
    | '/suivi/$id'
    | '/$slug/'
    | '/cuisine/'
    | '/$slug/suivi/$id'
    | '/_authenticated/admin/$slug'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/qrcodes'
    | '/_authenticated/espace/factures'
    | '/_authenticated/espace/tableau-de-bord'
    | '/api/public/lyra-ipn'
    | '/api/public/manifest'
    | '/api/public/mollie-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/espace/'
    | '/_authenticated/espace/$slug/carte'
    | '/_authenticated/espace/$slug/clients'
    | '/_authenticated/espace/$slug/equipe'
    | '/_authenticated/espace/$slug/livraison'
    | '/_authenticated/espace/$slug/qr'
    | '/_authenticated/espace/$slug/reglages'
    | '/_authenticated/espace/$slug/reservations'
    | '/api/public/push/message'
    | '/api/public/restaurant-banner/$id'
    | '/api/public/vapi/$restaurantId'
    | '/_authenticated/espace/$slug/'
    | '/api/public/menu-photo/$restaurantId/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRouteWithChildren
  AgenceRoute: typeof AgenceRoute
  CommandeRoute: typeof CommandeRoute
  ConnexionRoute: typeof ConnexionRoute
  DesabonnementRoute: typeof DesabonnementRoute
  LivreurRoute: typeof LivreurRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiMenuPhotoGenerateRoute: typeof ApiMenuPhotoGenerateRoute
  CuisineSplatRoute: typeof CuisineSplatRoute
  SuiviIdRoute: typeof SuiviIdRoute
  CuisineIndexRoute: typeof CuisineIndexRoute
  ApiPublicLyraIpnRoute: typeof ApiPublicLyraIpnRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicMollieWebhookRoute: typeof ApiPublicMollieWebhookRoute
  ApiPublicPushMessageRoute: typeof ApiPublicPushMessageRoute
  ApiPublicRestaurantBannerIdRoute: typeof ApiPublicRestaurantBannerIdRoute
  ApiPublicVapiRestaurantIdRoute: typeof ApiPublicVapiRestaurantIdRoute
  ApiPublicMenuPhotoRestaurantIdFileRoute: typeof ApiPublicMenuPhotoRestaurantIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence': {
      id: '/agence'
      path: '/agence'
      fullPath: '/agence'
      preLoaderRoute: typeof AgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desabonnement': {
      id: '/desabonnement'
      path: '/desabonnement'
      fullPath: '/desabonnement'
      preLoaderRoute: typeof DesabonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreur': {
      id: '/livreur'
      path: '/livreur'
      fullPath: '/livreur'
      preLoaderRoute: typeof LivreurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/borne': {
      id: '/$slug/borne'
      path: '/borne'
      fullPath: '/$slug/borne'
      preLoaderRoute: typeof SlugBorneRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/cgv': {
      id: '/$slug/cgv'
      path: '/cgv'
      fullPath: '/$slug/cgv'
      preLoaderRoute: typeof SlugCgvRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/commande': {
      id: '/$slug/commande'
      path: '/commande'
      fullPath: '/$slug/commande'
      preLoaderRoute: typeof SlugCommandeRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/confidentialite': {
      id: '/$slug/confidentialite'
      path: '/confidentialite'
      fullPath: '/$slug/confidentialite'
      preLoaderRoute: typeof SlugConfidentialiteRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/cookies': {
      id: '/$slug/cookies'
      path: '/cookies'
      fullPath: '/$slug/cookies'
      preLoaderRoute: typeof SlugCookiesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/cuisine': {
      id: '/$slug/cuisine'
      path: '/cuisine'
      fullPath: '/$slug/cuisine'
      preLoaderRoute: typeof SlugCuisineRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/mentions-legales': {
      id: '/$slug/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/$slug/mentions-legales'
      preLoaderRoute: typeof SlugMentionsLegalesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/reserver': {
      id: '/$slug/reserver'
      path: '/reserver'
      fullPath: '/$slug/reserver'
      preLoaderRoute: typeof SlugReserverRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/menu-photo-generate': {
      id: '/api/menu-photo-generate'
      path: '/api/menu-photo-generate'
      fullPath: '/api/menu-photo-generate'
      preLoaderRoute: typeof ApiMenuPhotoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine/': {
      id: '/cuisine/'
      path: '/cuisine'
      fullPath: '/cuisine/'
      preLoaderRoute: typeof CuisineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine/$': {
      id: '/cuisine/$'
      path: '/cuisine/$'
      fullPath: '/cuisine/$'
      preLoaderRoute: typeof CuisineSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$id': {
      id: '/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/suivi/$id'
      preLoaderRoute: typeof SuiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/suivi/$id': {
      id: '/$slug/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/$slug/suivi/$id'
      preLoaderRoute: typeof SlugSuiviIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$slug': {
      id: '/_authenticated/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AuthenticatedAdminSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/qrcodes': {
      id: '/_authenticated/admin/qrcodes'
      path: '/qrcodes'
      fullPath: '/admin/qrcodes'
      preLoaderRoute: typeof AuthenticatedAdminQrcodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/espace'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/factures': {
      id: '/_authenticated/espace/factures'
      path: '/espace/factures'
      fullPath: '/espace/factures'
      preLoaderRoute: typeof AuthenticatedEspaceFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/tableau-de-bord': {
      id: '/_authenticated/espace/tableau-de-bord'
      path: '/espace/tableau-de-bord'
      fullPath: '/espace/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedEspaceTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/lyra-ipn': {
      id: '/api/public/lyra-ipn'
      path: '/api/public/lyra-ipn'
      fullPath: '/api/public/lyra-ipn'
      preLoaderRoute: typeof ApiPublicLyraIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mollie-webhook': {
      id: '/api/public/mollie-webhook'
      path: '/api/public/mollie-webhook'
      fullPath: '/api/public/mollie-webhook'
      preLoaderRoute: typeof ApiPublicMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace/$slug/': {
      id: '/_authenticated/espace/$slug/'
      path: '/espace/$slug'
      fullPath: '/espace/$slug/'
      preLoaderRoute: typeof AuthenticatedEspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/carte': {
      id: '/_authenticated/espace/$slug/carte'
      path: '/espace/$slug/carte'
      fullPath: '/espace/$slug/carte'
      preLoaderRoute: typeof AuthenticatedEspaceSlugCarteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/clients': {
      id: '/_authenticated/espace/$slug/clients'
      path: '/espace/$slug/clients'
      fullPath: '/espace/$slug/clients'
      preLoaderRoute: typeof AuthenticatedEspaceSlugClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/equipe': {
      id: '/_authenticated/espace/$slug/equipe'
      path: '/espace/$slug/equipe'
      fullPath: '/espace/$slug/equipe'
      preLoaderRoute: typeof AuthenticatedEspaceSlugEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/livraison': {
      id: '/_authenticated/espace/$slug/livraison'
      path: '/espace/$slug/livraison'
      fullPath: '/espace/$slug/livraison'
      preLoaderRoute: typeof AuthenticatedEspaceSlugLivraisonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/qr': {
      id: '/_authenticated/espace/$slug/qr'
      path: '/espace/$slug/qr'
      fullPath: '/espace/$slug/qr'
      preLoaderRoute: typeof AuthenticatedEspaceSlugQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/reglages': {
      id: '/_authenticated/espace/$slug/reglages'
      path: '/espace/$slug/reglages'
      fullPath: '/espace/$slug/reglages'
      preLoaderRoute: typeof AuthenticatedEspaceSlugReglagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace/$slug/reservations': {
      id: '/_authenticated/espace/$slug/reservations'
      path: '/espace/$slug/reservations'
      fullPath: '/espace/$slug/reservations'
      preLoaderRoute: typeof AuthenticatedEspaceSlugReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/push/message': {
      id: '/api/public/push/message'
      path: '/api/public/push/message'
      fullPath: '/api/public/push/message'
      preLoaderRoute: typeof ApiPublicPushMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/restaurant-banner/$id': {
      id: '/api/public/restaurant-banner/$id'
      path: '/api/public/restaurant-banner/$id'
      fullPath: '/api/public/restaurant-banner/$id'
      preLoaderRoute: typeof ApiPublicRestaurantBannerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vapi/$restaurantId': {
      id: '/api/public/vapi/$restaurantId'
      path: '/api/public/vapi/$restaurantId'
      fullPath: '/api/public/vapi/$restaurantId'
      preLoaderRoute: typeof ApiPublicVapiRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/menu-photo/$restaurantId/$file': {
      id: '/api/public/menu-photo/$restaurantId/$file'
      path: '/api/public/menu-photo/$restaurantId/$file'
      fullPath: '/api/public/menu-photo/$restaurantId/$file'
      preLoaderRoute: typeof ApiPublicMenuPhotoRestaurantIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSlugRoute: typeof AuthenticatedAdminSlugRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminQrcodesRoute: typeof AuthenticatedAdminQrcodesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSlugRoute: AuthenticatedAdminSlugRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminQrcodesRoute: AuthenticatedAdminQrcodesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEspaceFacturesRoute: typeof AuthenticatedEspaceFacturesRoute
  AuthenticatedEspaceTableauDeBordRoute: typeof AuthenticatedEspaceTableauDeBordRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
  AuthenticatedEspaceSlugCarteRoute: typeof AuthenticatedEspaceSlugCarteRoute
  AuthenticatedEspaceSlugClientsRoute: typeof AuthenticatedEspaceSlugClientsRoute
  AuthenticatedEspaceSlugEquipeRoute: typeof AuthenticatedEspaceSlugEquipeRoute
  AuthenticatedEspaceSlugLivraisonRoute: typeof AuthenticatedEspaceSlugLivraisonRoute
  AuthenticatedEspaceSlugQrRoute: typeof AuthenticatedEspaceSlugQrRoute
  AuthenticatedEspaceSlugReglagesRoute: typeof AuthenticatedEspaceSlugReglagesRoute
  AuthenticatedEspaceSlugReservationsRoute: typeof AuthenticatedEspaceSlugReservationsRoute
  AuthenticatedEspaceSlugIndexRoute: typeof AuthenticatedEspaceSlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEspaceFacturesRoute: AuthenticatedEspaceFacturesRoute,
  AuthenticatedEspaceTableauDeBordRoute: AuthenticatedEspaceTableauDeBordRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  AuthenticatedEspaceSlugCarteRoute: AuthenticatedEspaceSlugCarteRoute,
  AuthenticatedEspaceSlugClientsRoute: AuthenticatedEspaceSlugClientsRoute,
  AuthenticatedEspaceSlugEquipeRoute: AuthenticatedEspaceSlugEquipeRoute,
  AuthenticatedEspaceSlugLivraisonRoute: AuthenticatedEspaceSlugLivraisonRoute,
  AuthenticatedEspaceSlugQrRoute: AuthenticatedEspaceSlugQrRoute,
  AuthenticatedEspaceSlugReglagesRoute: AuthenticatedEspaceSlugReglagesRoute,
  AuthenticatedEspaceSlugReservationsRoute:
    AuthenticatedEspaceSlugReservationsRoute,
  AuthenticatedEspaceSlugIndexRoute: AuthenticatedEspaceSlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SlugRouteChildren {
  SlugBorneRoute: typeof SlugBorneRoute
  SlugCgvRoute: typeof SlugCgvRoute
  SlugCommandeRoute: typeof SlugCommandeRoute
  SlugConfidentialiteRoute: typeof SlugConfidentialiteRoute
  SlugCookiesRoute: typeof SlugCookiesRoute
  SlugCuisineRoute: typeof SlugCuisineRoute
  SlugMentionsLegalesRoute: typeof SlugMentionsLegalesRoute
  SlugReserverRoute: typeof SlugReserverRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugSuiviIdRoute: typeof SlugSuiviIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugBorneRoute: SlugBorneRoute,
  SlugCgvRoute: SlugCgvRoute,
  SlugCommandeRoute: SlugCommandeRoute,
  SlugConfidentialiteRoute: SlugConfidentialiteRoute,
  SlugCookiesRoute: SlugCookiesRoute,
  SlugCuisineRoute: SlugCuisineRoute,
  SlugMentionsLegalesRoute: SlugMentionsLegalesRoute,
  SlugReserverRoute: SlugReserverRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugSuiviIdRoute: SlugSuiviIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRouteWithChildren,
  AgenceRoute: AgenceRoute,
  CommandeRoute: CommandeRoute,
  ConnexionRoute: ConnexionRoute,
  DesabonnementRoute: DesabonnementRoute,
  LivreurRoute: LivreurRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiMenuPhotoGenerateRoute: ApiMenuPhotoGenerateRoute,
  CuisineSplatRoute: CuisineSplatRoute,
  SuiviIdRoute: SuiviIdRoute,
  CuisineIndexRoute: CuisineIndexRoute,
  ApiPublicLyraIpnRoute: ApiPublicLyraIpnRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicMollieWebhookRoute: ApiPublicMollieWebhookRoute,
  ApiPublicPushMessageRoute: ApiPublicPushMessageRoute,
  ApiPublicRestaurantBannerIdRoute: ApiPublicRestaurantBannerIdRoute,
  ApiPublicVapiRestaurantIdRoute: ApiPublicVapiRestaurantIdRoute,
  ApiPublicMenuPhotoRestaurantIdFileRoute:
    ApiPublicMenuPhotoRestaurantIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
