/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugCommandeRouteImport } from './routes/$slug.commande'
import { Route as CuisineIndexRouteImport } from './routes/cuisine.index'
import { Route as SuiviIdRouteImport } from './routes/suivi.$id'
import { Route as SlugSuiviIdRouteImport } from './routes/$slug.suivi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCommandeRoute = SlugCommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => SlugRoute,
} as any)
const CuisineIndexRoute = CuisineIndexRouteImport.update({
  id: '/cuisine/',
  path: '/cuisine/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIdRoute = SuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSuiviIdRoute = SlugSuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug': typeof SlugIndexRoute
  '/cuisine': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/commande': typeof CommandeRoute
  '/connexion': typeof ConnexionRoute
  '/$slug/commande': typeof SlugCommandeRoute
  '/suivi/$id': typeof SuiviIdRoute
  '/$slug/': typeof SlugIndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/$slug/suivi/$id': typeof SlugSuiviIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/commande'
    | '/connexion'
    | '/$slug/commande'
    | '/suivi/$id'
    | '/$slug/'
    | '/cuisine/'
    | '/$slug/suivi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commande'
    | '/connexion'
    | '/$slug/commande'
    | '/suivi/$id'
    | '/$slug'
    | '/cuisine'
    | '/$slug/suivi/$id'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/commande'
    | '/connexion'
    | '/$slug/commande'
    | '/suivi/$id'
    | '/$slug/'
    | '/cuisine/'
    | '/$slug/suivi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  CommandeRoute: typeof CommandeRoute
  ConnexionRoute: typeof ConnexionRoute
  SuiviIdRoute: typeof SuiviIdRoute
  CuisineIndexRoute: typeof CuisineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/commande': {
      id: '/$slug/commande'
      path: '/commande'
      fullPath: '/$slug/commande'
      preLoaderRoute: typeof SlugCommandeRouteImport
      parentRoute: typeof SlugRoute
    }
    '/cuisine/': {
      id: '/cuisine/'
      path: '/cuisine'
      fullPath: '/cuisine/'
      preLoaderRoute: typeof CuisineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$id': {
      id: '/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/suivi/$id'
      preLoaderRoute: typeof SuiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/suivi/$id': {
      id: '/$slug/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/$slug/suivi/$id'
      preLoaderRoute: typeof SlugSuiviIdRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugCommandeRoute: typeof SlugCommandeRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugSuiviIdRoute: typeof SlugSuiviIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugCommandeRoute: SlugCommandeRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugSuiviIdRoute: SlugSuiviIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  CommandeRoute: CommandeRoute,
  ConnexionRoute: ConnexionRoute,
  SuiviIdRoute: SuiviIdRoute,
  CuisineIndexRoute: CuisineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
